<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ViewAndModifyEventDetails.aspx.cs" Inherits="ViewAndModifyEventDetails" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table  border="2" align="center"   width="60%" cellpadding ="5px">
        <tr>
            <th colspan="2">
               <br /> <h1>
                    Event Details</h1><br />
            </th>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <center><asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False"
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ename,edate"
                    EmptyDataText="Record Not Found!!!" OnPageIndexChanging="GridView1_PageIndexChanging"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting"
                    OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" PageSize="4"
                    BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" 
                        BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" 
                        Width="561px">
                    <Columns>
                     <asp:BoundField DataField ="ename" HeaderText ="Event Name" ReadOnly ="True" />
                      <asp:BoundField DataField ="etype" HeaderText ="Type" />
                      <asp:BoundField DataField ="description" HeaderText ="Description" />
                      
                      <asp:BoundField DataField ="venue" HeaderText ="Venue" />
                      <asp:BoundField DataField ="edate" HeaderText ="Event Date" DataFormatString ="{0:dd-MMM-yyyy}"  HtmlEncode ="False"  ReadOnly ="true" />
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                    <RowStyle BackColor="White" />
                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#808080" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#383838" />
                </asp:GridView></center>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <asp:Label ID="Label1" runat="server" Font-Bold="True" Text="Label"></asp:Label>&nbsp;
            </td>
        </tr>
    </table>
</asp:Content>

